### ISSUE TITLE
Video is not centered.

### ISSUE THREAD

**Issue by Darth-Nastro** [PacktPublishing/Beginning-Cpp-Game-Programming-Second-Edition#1]
When creating the game according to the book (all the code is exactly the same) this issue happens with the video when i open it 
Attached is the full code as well as the video of the issue

[Video issue.zip](https://github.com/PacktPublishing/Beginning-Cpp-Game-Programming-Second-Edition/files/5372377/Video.issue.zip)

**Comment by shubham763** [comment]
Hi @Darth-Nastro 

In the line VideoMode vm(1920, 1080)

Try changing the 1920, 1080 to whatever the resolution of your screen is. If you have a very low-resolution screen then see the “important note” in the section “Understanding screen and internal coordinates”.

Regards,
Shubham
