### ISSUE TITLE
Space Invaders

### ISSUE THREAD

**Issue by amaraoussama94** [PacktPublishing/Beginning-Cpp-Game-Programming-Second-Edition#7]
At the end of chapter 19  we  try to run the  code but  the button position and  mouse clicked  pixel does not  match maybe because the view

**Comment by shruthis-shetty** [comment]
> At the end of chapter 19 we try to run the code but the button position and mouse clicked pixel does not match maybe because the view

Hey @amaraoussama94 , do you need any suggestion from the author on this?
