### ISSUE TITLE
Fullscreen doesn't work on mac OS and View has to be set to match background size

### ISSUE THREAD

**Issue by dogruis** [PacktPublishing/Beginning-Cpp-Game-Programming-Second-Edition#9]
https://github.com/PacktPublishing/Beginning-Cpp-Game-Programming-Second-Edition/blob/df1d217b4479bb396741406789c75d178641be69/Chapter02/code/Timber.cpp#L13

I had to fix the code like this here

```
    // Create a video mode object
    VideoMode vm(1920, 1080);
    // Create and open a window for the game
    RenderWindow window(vm, "Timber!!!", Style::Default);
    // Set the window view to match the resolution
    View view(FloatRect(0, 0, 1920, 1080));
    window.setView(view);
```

**Comment by bsingha27** [comment]
Hi @dogruis, 
Glad that you found a solution. We have updated the README with the correct code in the Errata section.
We're closing this issue! If you face any further issues on any chapter, please feel free to open a new one.
Thanks.

**Comment by dogruis** [comment]
@bsingha27 Can you also run through the third edition here:
https://github.com/PacktPublishing/Beginning-C-Game-Programming-Third-Edition/issues
